add springboot and micronaut grpc bff example
ZupIT/beagle-helpers pull request #66
Opened 2021-04-27 14:58 UTC by luismaximozup

2021-04-27 15:00 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-05-05 12:45 UTC, LG95 commented on micronaut-grpc-bff/README.md
> +Ready! Application will be standing at door 50051, enjoy it!
```suggestion
That's it! The application will be up at localhost:50051, enjoy it!
```

2021-05-05 12:47 UTC, LG95 commented on micronaut-grpc-bff/README.md
> +      - **"name"** parameter is mandatory and must contain a valid string referring to the name of a registered screen.
```suggestion
      - **"name"** is a mandatory parameter and must contain a valid string referring to the name of a registered screen. For this application, the available names are "Home" and "Text".
```

2021-05-05 12:49 UTC, LG95 commented on micronaut-grpc-bff/README.md
> +      - **"Parameters"** is optional and contains a string that is used in the message of the Text component of the Home Screen
```suggestion
      - **`parameters`** is optional and contains a string that is used in the message of the `Text` component of the home screen
```

2021-05-05 12:52 UTC, LG95 commented on micronaut-grpc-bff/gradle.properties
> +kotlinVersion=1.4.31
Why not place the version of all dependencies here?

2021-05-05 13:38 UTC, luismaximozup commented on micronaut-grpc-bff/gradle.properties
> +kotlinVersion=1.4.31
Ok

2021-05-05 14:19 UTC, LG95 commented on spring-grpc-bff/README.md
> +            - **"Parameters"** is optional and contains a string that is used in Text component message on Home Screen
```suggestion
That's it! The application will be up at localhost:50051, enjoy it!

### Services available:

- ScreenService
  - method: getScreen
  - request: ```{
      "name": "String",  
      "parameters": "String"  
    }```
    - Description: This method searches for one or more Screen Builders registered in the BeagleScreenService class provided by lib.   
      - **`name`** is a mandatory parameter and must contain a valid string referring to the name of a registered screen. For this application, the available names are "Home" and "Text".
      - **`parameters`** is optional and contains a string that is used in the message of the `Text` component of the home screen
```

2021-05-05 20:09 UTC, LG95 requested changes
Why is gradle wrapper added to the project's root and `grpc-backend-lib` in this branch?

2021-05-06 17:20 UTC, luismaximozup commented
> Why is gradle wrapper added to the project's root and `grpc-backend-lib` in this branch?

Because another PR will be opened refactoring and joining within the backend. If everything was done together initially, it would be a big PR making the review process more difficult.

2021-05-06 20:39 UTC, LG95 commented
> > Why is gradle wrapper added to the project's root and `grpc-backend-lib` in this branch?
> 
> Because another PR will be opened refactoring and joining within the backend. If everything was done together initially, it would be a big PR making the review process more difficult.

I see. Truly larger PRs are harder to review, but when splitting the change across branches, make sure they are independent, otherwise all the changes need to be analyzed together and might as well have been a singe PR.
This explains the `grpc-backend-lib` directory, but what about the addition of gradle wrapper to the root?

2021-05-06 20:42 UTC, LG95 commented on micronaut-grpc-bff/src/main/kotlin/br/com/zup/interceptor/MyInterceptor.kt
> +import br.com.zup.grpc.BeagleHeadersInterceptor
Where is this defined? I can't find it in any file in this PR nor in #65

2021-05-06 20:49 UTC, LG95 commented on spring-grpc-bff/src/main/kotlin/br/com/zup/grpcbff/service/MyBeagleScreenService.kt
> +        val requestHeaders = BeagleHeadersInterceptor.HEADERS_VALUE.get()
Why not create a screen that use these headers for a more complete example?

2021-05-06 21:59 UTC, luismaximozup commented on micronaut-grpc-bff/src/main/kotlin/br/com/zup/interceptor/MyInterceptor.kt
> +import br.com.zup.grpc.BeagleHeadersInterceptor
done

2021-05-06 22:02 UTC, luismaximozup commented on spring-grpc-bff/src/main/kotlin/br/com/zup/grpcbff/service/MyBeagleScreenService.kt
> +        val requestHeaders = BeagleHeadersInterceptor.HEADERS_VALUE.get()
nice suggestion, I will think of something

2021-05-10 15:05 UTC, LG95 commented on micronaut-grpc-bff/src/main/kotlin/br/com/zup/interceptor/ServerInterceptorFactory.kt
> +        return  OrderedServerInterceptor ( MyInterceptor(), 10 ); // (3)
What is this comment about?

2021-05-10 18:15 UTC, luismaximozup commented on micronaut-grpc-bff/src/main/kotlin/br/com/zup/interceptor/ServerInterceptorFactory.kt
> +        return  OrderedServerInterceptor ( MyInterceptor(), 10 ); // (3)
fixed

2021-05-13 15:06 UTC, LG95 commented on micronaut-grpc-bff/src/main/kotlin/br/com/zup/screen/SplashScreen.kt
> +                    text = "Button with Appearance, style and headers: ${this.headers["content-type"]}",
```suggestion
                    text = "Button with Appearance, style and content type: ${this.headers["content-type"]}",
```

2021-05-13 15:06 UTC, LG95 commented on spring-grpc-bff/src/main/kotlin/br/com/zup/grpcbff/screen/SplashScreen.kt
> +                    text = "Button with Appearance, style and headers: ${this.headers["content-type"]}",
```suggestion
                    text = "Button with Appearance, style and content type: ${this.headers["content-type"]}",
```

2021-05-13 15:07 UTC, LG95 approved these changes

2021-05-14 21:19 UTC, LG95 approved these changes

2021-05-14 21:36 UTC, merged