Support gRPC Protocol for Beagle Web through a proxy server
ZupIT/beagle-helpers pull request #68
Opened 2021-04-30 17:25 UTC by arthurbleilzup

2021-04-30 17:31 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  2 Warnings: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-05-04 19:47 UTC, Tiagoperes requested changes
Wow, so many tests! Good work!

As a general commentary, sometimes you throw errors as strings, without creating an object that extends the Error class. This is unusual. You also sometimes create the error class. I didn't notice any pattern for using or not `Error(message)`. Can you please explain?

Now we need a good documentation for this, because GRPC can't work natively for WEB, I imagine our "installation guide" will be more complicated than the others.

Also, we need a github action to run all these tests...

2021-05-04 19:47 UTC, Tiagoperes commented on web/beagle-grpc/src/lib/utils/request.ts
> +}
Too many nested ifs. Suggestion:

```typescript
if (typeof requestInfo === 'string') return { url: requestInfo }
if (requestInfo && typeof requestInfo === 'object') {
  const { url, method, headers, body } = requestInfo
  return { url, method, headers, body }
}
return null
```

2021-05-04 19:47 UTC, Tiagoperes commented on web/beagle-grpc/__tests__/lib/element.spec.ts
> +    test('it should return a BeagleUIElement with style', () => {
Have you switched the implementation of this test with the next one?

2021-05-04 20:43 UTC, arthurbleilzup commented on web/beagle-grpc/__tests__/lib/element.spec.ts
> +    test('it should return a BeagleUIElement with style', () => {
yes...

2021-05-04 20:45 UTC, arthurbleilzup commented
> Wow, so many tests! Good work!
> 
> As a general commentary, sometimes you throw errors as strings, without creating an object that extends the Error class. This is unusual. You also sometimes create the error class. I didn't notice any pattern for using or not `Error(message)`. Can you please explain?
> 
> Now we need a good documentation for this, because GRPC can't work natively for WEB, I imagine our "installation guide" will be more complicated than the others.
> 
> Also, we need a github action to run all these tests...

Because when I was throwing those errors I just logged them and the application was exited, but right now with your point of view, it make sense to be an Error object, so I fixed it

2021-05-05 12:15 UTC, Tiagoperes submitted a review, later dismissed

2021-05-31 13:31 UTC, Tiagoperes approved these changes

2021-05-31 13:32 UTC, merged