Fix/backend directory
ZupIT/beagle-helpers pull request #74
Opened 2021-05-21 19:58 UTC by luismaximozup

2021-05-21 20:00 UTC, botbeaglezup commented
<!--
  0 Errors
  2 Warnings: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-05-26 17:14 UTC, ze12augusto approved these changes

2021-05-28 16:37 UTC, botbeaglezup commented
<!--
  0 Errors
  14 Warnings: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          14 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-defaults/build.gradle#L59">android/beagle-defaults/build.gradle#L59</a> - A newer version of org.jetbrains.kotlinx:kotlinx-coroutines-android than 1.3.9 is available: 1.4.2</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-defaults/build.gradle#L63">android/beagle-defaults/build.gradle#L63</a> - A newer version of org.jetbrains.kotlinx:kotlinx-coroutines-test than 1.3.9 is available: 1.4.2</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-defaults/build.gradle#L66">android/beagle-defaults/build.gradle#L66</a> - A newer version of androidx.test:core than 1.4.0-alpha04 is available: 1.4.0-beta01</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-defaults/build.gradle#L67">android/beagle-defaults/build.gradle#L67</a> - A newer version of androidx.test:runner than 1.4.0-alpha04 is available: 1.4.0-beta01</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-defaults/build.gradle#L70">android/beagle-defaults/build.gradle#L70</a> - A newer version of io.mockk:mockk than 1.10.2 is available: 1.10.6</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-defaults/build.gradle#L72">android/beagle-defaults/build.gradle#L72</a> - A newer version of androidx.test.ext:junit than 1.1.3-alpha04 is available: 1.1.3-beta01</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L62">android/beagle-scaffold/build.gradle#L62</a> - A newer version of androidx.core:core-ktx than 1.3.2 is available: 1.5.0</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L63">android/beagle-scaffold/build.gradle#L63</a> - A newer version of androidx.appcompat:appcompat than 1.2.0 is available: 1.3.0</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L67">android/beagle-scaffold/build.gradle#L67</a> - A newer version of org.jetbrains.kotlinx:kotlinx-coroutines-android than 1.3.9 is available: 1.4.2</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L72">android/beagle-scaffold/build.gradle#L72</a> - A newer version of org.jetbrains.kotlinx:kotlinx-coroutines-test than 1.3.9 is available: 1.4.2</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L75">android/beagle-scaffold/build.gradle#L75</a> - A newer version of androidx.test:core than 1.4.0-alpha04 is available: 1.4.0-beta01</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L76">android/beagle-scaffold/build.gradle#L76</a> - A newer version of androidx.test:runner than 1.4.0-alpha04 is available: 1.4.0-beta01</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L79">android/beagle-scaffold/build.gradle#L79</a> - A newer version of io.mockk:mockk than 1.10.2 is available: 1.10.6</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-helpers/blob/716b958710fb23c8afc9db81bbb32d7e1c504c4d/android/beagle-scaffold/build.gradle#L81">android/beagle-scaffold/build.gradle#L81</a> - A newer version of androidx.test.ext:junit than 1.1.3-alpha04 is available: 1.1.3-beta01</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-06-04 14:04 UTC, ze12augusto requested changes

2021-06-04 14:04 UTC, ze12augusto commented on backend/examples/spring-grpc-bff/build.gradle.kts
> +	implementation("br.com.zup.beagle:beagle-grpc-backend:0.0.1")
You should use grpcVersion variable instead of hard code 0.0.1

2021-06-04 14:04 UTC, ze12augusto commented on backend/gradle.properties
> +VERSION_NAME=0.0.2-maximo
Change VERSION_NAME property to default value, like 0.0.1

2021-06-07 17:22 UTC, luismaximozup commented on backend/gradle.properties
> +VERSION_NAME=0.0.2-maximo
done

2021-06-07 19:27 UTC, closed without merging